Metrics/LineLength:
  Max: 100

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude:
    - "config/environment.rb"
    - "spec/support/environment_helper.rb"

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/LeadingCommentSpace:
  Exclude:
    - Gemfile

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/DotPosition:
  EnforcedStyle: trailing

Metrics/ClassLength:
  Max: 100
