language: ruby
cache:
  directories:
    - vendor/bundle
    - node_modules
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
script:
  - bundle exec rspec && (npm run semantic-release || true)

